[project]
name = "stereo-calibration-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=1.26.0",
    "opencv-python>=4.11.0.86",
    "pyqt6>=6.10.1",
    "pyyaml>=6.0.3",
]
